#!/bin/bash

BUILD_TYPES="Release"
BASEDIR=`pwd`
MAKE_DATE=$(date)
VERSION_NUM="3.0"
CMAKEOPTIONS="$@"
OSTYPE=`uname`

for build_type in ${BUILD_TYPES}
do
    BUILD_DIR=${BASEDIR}/build.${build_type}

    echo "Configuring ${build_type} build in ${BUILD_DIR}"

    mkdir -p ${BUILD_DIR}
    cd ${BUILD_DIR} 
    cmake -DCMAKE_BUILD_TYPE=${build_type} ${CMAKEOPTIONS} ..
done

echo -e "\nGeneration of build files completed."
for build_type in ${BUILD_TYPES}
do
    BUILD_DIR=${BASEDIR}/build.${build_type}
    
    echo "-- ${build_type} in ${BUILD_DIR}"
done
